"""
Django settings for wisemark_site project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root (wisemark_site/) so DB_*, SECRET_KEY, etc. are set
_env_path = BASE_DIR / '.env'
if _env_path.exists():
    with open(_env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, _, value = line.partition('=')
                k = key.strip()
                v = value.strip().strip('"').strip("'")
                os.environ[k] = v  # .env overrides so it always loads

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    h.strip().rstrip('/') for h in
    os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,wisemark-production.up.railway.app,.railway.app,www.wisemarkhq.com, wisemarkhq.com').split(',')
    if h.strip()
]

# Optional: canonical public URL for share links (e.g. https://www.wisemarkhq.com).
# When set, generated share links use this base so they work when opened from any browser/device.
SITE_URL = (os.environ.get('SITE_URL') or '').strip().rstrip('/') or None

# Stripe
STRIPE_PRODUCT_ID = os.environ.get('STRIPE_PRODUCT_ID', '')
STRIPE_PK = os.environ.get('STRIPE_PK', '')
STRIPE_SK = os.environ.get('STRIPE_SK', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# CSRF: allow same-origin requests from these origins (Django 4+ checks Origin header)
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in
    os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:8000,http://127.0.0.1:8000,https://wisemark-production.up.railway.app, https://wisemarkhq.com, https://www.wisemarkhq.com'
    ).split(',')
    if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'accounts',
    'documents',
    'pages',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
if os.environ.get('CORS_ORIGINS'):
    CORS_ALLOWED_ORIGINS = [o.strip() for o in os.environ['CORS_ORIGINS'].split(',') if o.strip()]

MIDDLEWARE = [
    'wisemark_site.middleware.SecureCookieMiddleware',
    'wisemark_site.middleware.SecurityHeadersMiddleware',
    'wisemark_site.middleware.ErrorReferenceMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wisemark_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wisemark_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# If DB_HOST, DB_NAME, DB_USER are set in .env → use Postgres. Otherwise → db.sqlite3.

_db_host = os.environ.get('DB_HOST')
_db_name = os.environ.get('DB_NAME')
_db_user = os.environ.get('DB_USER')
_db_password = os.environ.get('DB_PASSWORD')
_db_port = os.environ.get('DB_PORT', '5432')

if _db_host and _db_name and _db_user is not None:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db_name,
            'USER': _db_user,
            'PASSWORD': _db_password or '',
            'HOST': _db_host,
            'PORT': _db_port,
            'CONN_MAX_AGE': 600,
            # Railway and most cloud Postgres require SSL
            'OPTIONS': {
                'connect_timeout': 30,
                'sslmode': 'require',
            },
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# S3 for PDF storage (optional). If AWS_STORAGE_BUCKET_NAME is set, new PDFs go to S3.
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = (os.environ.get('AWS_STORAGE_BUCKET_NAME') or '').strip() or None
AWS_S3_REGION_NAME = (os.environ.get('AWS_S3_REGION_NAME') or '').strip() or 'eu-west-2'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# When behind a reverse proxy (e.g. Railway), the proxy terminates HTTPS and forwards
# the request as HTTP. Trust X-Forwarded-Proto so Django sees the request as HTTPS
# and generates secure URLs, cookies, and redirects.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Secure cookies must be set in production so the browser marks the connection secure.
# Without these, Chrome shows "Not Secure" even with a valid HTTPS certificate.
_use_secure_cookies = os.environ.get('USE_SECURE_COOKIES', '').lower() in ('1', 'true', 'yes')
if not DEBUG or _use_secure_cookies:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# Production security (when DEBUG is False)
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() in ('1', 'true', 'yes')
    # HSTS: tell browsers to always use HTTPS for this domain (helps Chrome show secure)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Email Settings — support (default Django mail)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
SUPPORT_EMAIL_HOST = 'smtp.office365.com'
SUPPORT_EMAIL_PORT = 587
SUPPORT_EMAIL_USE_TLS = True
SUPPORT_EMAIL_USE_SSL = False
SUPPORT_EMAIL_HOST_USER = os.environ.get('SUPPORT_EMAIL_HOST_USER')
SUPPORT_EMAIL_HOST_PASSWORD = os.environ.get('SUPPORT_EMAIL_HOST_PASSWORD')
SUPPORT_DEFAULT_FROM_EMAIL = os.environ.get('SUPPORT_DEFAULT_FROM_EMAIL')

# Email Settings — accounts (sign-in codes)

ACCOUNTS_EMAIL_HOST = 'smtp.office365.com'
ACCOUNTS_EMAIL_PORT = 587
ACCOUNTS_EMAIL_USE_TLS = True
ACCOUNTS_EMAIL_HOST_USER = os.environ.get('ACCOUNTS_EMAIL_HOST_USER')
ACCOUNTS_EMAIL_HOST_PASSWORD = os.environ.get('ACCOUNTS_EMAIL_HOST_PASSWORD')
ACCOUNTS_DEFAULT_FROM_EMAIL = os.environ.get('ACCOUNTS_DEFAULT_FROM_EMAIL')

# Email — TB (welcome email from tb@wisemarkhq.com)
TB_EMAIL_HOST_USER = os.environ.get('TB_EMAIL_HOST_USER')
TB_EMAIL_HOST_PASSWORD = os.environ.get('TB_EMAIL_HOST_PASSWORD')
TB_DEFAULT_FROM_EMAIL = os.environ.get('TB_DEFAULT_FROM_EMAIL')

# Logging: ensure errors and user reports are visible (console + optional file)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'wisemark_site': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}