# Generated by Django 6.0.2 on 2026-02-14 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_hash', models.CharField(help_text='SHA-256 hash of the PDF file', max_length=64)),
                ('filename', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'pdf_hash')},
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('position_data', models.JSONField(help_text='JSON containing selection range data for re-rendering')),
                ('color', models.CharField(choices=[('yellow', 'Key Metrics'), ('green', 'Competitive Advantages'), ('blue', 'Management Questions'), ('pink', 'Investment Risks'), ('orange', 'Commercial DD')], default='yellow', max_length=10)),
                ('highlighted_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='documents.document')),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='documents.highlight')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
