# Generated by Django 6.0.2 on 2026-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='color_labels',
            field=models.JSONField(blank=True, default=dict, help_text='Override topic names per color, e.g. {"orange": "Legal DD"}'),
        ),
    ]
