# Generated by Django 5.2.11 on 2026-02-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_add_storage_location_and_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(help_text='Display name (editable)', max_length=500),
        ),
    ]
