# Generated by Django (WiseMark refactor: Color as FK)

from django.db import migrations, models
import django.db.models.deletion


def create_colors_and_migrate_document_colors(apps, schema_editor):
    Color = apps.get_model('documents', 'Color')
    Document = apps.get_model('documents', 'Document')
    DocumentColor = apps.get_model('documents', 'DocumentColor')
    # Create the 5 colours in fixed order (yellow id=1 for default)
    for key, default_name in [
        ('yellow', 'Key Metrics'),
        ('green', 'Competitive Advantages'),
        ('blue', 'Management Questions'),
        ('pink', 'Investment Risks'),
        ('orange', 'Commercial DD'),
    ]:
        Color.objects.get_or_create(key=key, defaults={'default_name': default_name})
    # Migrate Document.color_labels -> DocumentColor rows
    key_to_color = {c.key: c for c in Color.objects.all()}
    for doc in Document.objects.all():
        labels = getattr(doc, 'color_labels', None) or {}
        for key, custom_name in labels.items():
            if isinstance(custom_name, str) and custom_name.strip() and key in key_to_color:
                DocumentColor.objects.get_or_create(
                    document=doc,
                    color=key_to_color[key],
                    defaults={'custom_name': custom_name.strip()},
                )


def backfill_highlight_color_fk(apps, schema_editor):
    Color = apps.get_model('documents', 'Color')
    Highlight = apps.get_model('documents', 'Highlight')
    key_to_color = {c.key: c for c in Color.objects.all()}
    for h in Highlight.objects.all():
        old_color = getattr(h, 'color', None)  # char value e.g. 'yellow'
        if not old_color:
            old_color = 'yellow'
        if old_color in key_to_color:
            h.color_fk = key_to_color[old_color]
            h.save(update_fields=['color_fk'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('default_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DocumentColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_colors', to='documents.document')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_colors', to='documents.color')),
            ],
            options={
                'ordering': ['color__key'],
                'unique_together': {('document', 'color')},
            },
        ),
        migrations.RunPython(create_colors_and_migrate_document_colors, noop_reverse),
        migrations.RemoveField(
            model_name='document',
            name='color_labels',
        ),
        migrations.AddField(
            model_name='highlight',
            name='color_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='highlights', to='documents.color'),
        ),
        migrations.RunPython(backfill_highlight_color_fk, noop_reverse),
        migrations.RemoveField(
            model_name='highlight',
            name='color',
        ),
        migrations.RenameField(
            model_name='highlight',
            old_name='color_fk',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='highlight',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='highlights', to='documents.color'),
            preserve_default=False,
        ),
    ]
