# Generated by Django 5.2.11 on 2026-02-19 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_system_highlight_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='color_key',
            field=models.CharField(default='yellow', help_text='Raw colour key, supports both legacy and custom preset keys.', max_length=60),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='highlights', to='documents.color'),
        ),
    ]
