# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_last_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='color_display_name',
            field=models.CharField(
                blank=True,
                help_text='Display name when highlight was created. Shown with (Deleted) when category was removed from lens.',
                max_length=255,
                null=True,
            ),
        ),
    ]
