# Generated by Django

from django.db import migrations


def forwards(apps, schema_editor):
    Highlight = apps.get_model('documents', 'Highlight')
    HighlightPreset = apps.get_model('documents', 'HighlightPreset')
    PresetColor = apps.get_model('documents', 'PresetColor')
    Document = apps.get_model('documents', 'Document')

    for h in Highlight.objects.select_related('document').iterator():
        if h.color_display_name:
            continue
        doc = h.document
        preset = None
        if doc.highlight_preset_id:
            preset = HighlightPreset.objects.filter(pk=doc.highlight_preset_id).first()
        if not preset:
            preset = HighlightPreset.objects.filter(user__isnull=True).order_by('name').first()
        if preset:
            pc = PresetColor.objects.filter(preset=preset, key=h.color_key).first()
            if pc:
                h.color_display_name = pc.display_name
                h.save(update_fields=['color_display_name'])


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_highlight_color_display_name'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
